### ISSUE TITLE
Php8.1 incompatibility

### ISSUE THREAD

**Issue by musabatas** [Paybyway/visma-pay-magento2#1]
There are some issues with PHP deprecated functions. We are using Magento 2.4.5-p1 with php8.1. Will there be an update soon?

**Comment by juusohautapaakkanen** [comment]
Hi, and thanks for your patience. We do have an ongoing investigation into upgrading the plugin for up-to-date versions of PHP and Magento, but unfortunately at this time cannot give a time frame for when an update would be available.

**Comment by jurvi** [comment]
Literally 2 hours of work to make this PHP 8.1 & Magento 2.4.5 compatible. And that includes setting up the dev env, install, fix, testing, and release.
